/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distsys.kevms;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import generated.grpc.CA.maritimesafety.*;
import generated.grpc.CA.touroperations.*;
import generated.grpc.CA.stafftraining.*;

// Import the StreamObserver for the Client-Streaming functionality
import io.grpc.stub.StreamObserver;

// Import for the advanced gRPC requirements
import io.grpc.StatusRuntimeException;
import io.grpc.Metadata;
import io.grpc.stub.MetadataUtils;
import io.grpc.Context;
import io.grpc.Status;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author andre
 */
public class KEVMS_GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KEVMS_GUI.class.getName());
    private String safetyHost;
    private int safetyPort;
    private String tourHost;
    private int tourPort;
    private String trainingHost;
    private int trainingPort;
            
    /**
     * Creates new form KEVMS_GUI
     */
    public KEVMS_GUI() {
        initComponents();
        // Custom styling for the Home Tab message
        txtHomeWelcome.setText("Welcome to KEVMS\n\n"
                + "Use the buttons below or the tabs above to access:\n"
                + "1. Maritime Safety: Real-time sea conditions and vessel alerts.\n"
                + "2. Tour Operations: Fleet efficiency and telemetry tracking.\n"
                + "3. Staff Training: Interactive navigation simulation for trainees.");
        txtHomeWelcome.setWrapStyleWord(true);
        txtHomeWelcome.setLineWrap(true);
        txtHomeWelcome.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        btnNavSafety = new javax.swing.JButton();
        btnNavTour = new javax.swing.JButton();
        btnNavTraining = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtHomeWelcome = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        findMaritimeSafetyServicebtn = new javax.swing.JButton();
        lblStatusSafety = new javax.swing.JLabel();
        txtAreaCode = new javax.swing.JTextField();
        checkSeaConditionBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultSafety = new javax.swing.JTextArea();
        txtVesselId = new javax.swing.JTextField();
        startMonitoringBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        findTourOperationsServicebtn = new javax.swing.JButton();
        lblStatusTour = new javax.swing.JLabel();
        txtStaffId = new javax.swing.JTextField();
        btnGetPerformance = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultTour = new javax.swing.JTextArea();
        btnStartVoyage = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        findTrainingHubServicebtn = new javax.swing.JButton();
        lblStatusTraining = new javax.swing.JLabel();
        txtTrainingStaffId = new javax.swing.JTextField();
        btnStartTraining = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResultTraining = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setForeground(new java.awt.Color(153, 153, 153));

        btnNavSafety.setText("Maritime Safety");
        btnNavSafety.addActionListener(this::btnNavSafetyActionPerformed);

        btnNavTour.setText("Tour Operations");
        btnNavTour.addActionListener(this::btnNavTourActionPerformed);

        btnNavTraining.setText("Staff Training");
        btnNavTraining.addActionListener(this::btnNavTrainingActionPerformed);

        jLabel3.setText("KEVMS");

        txtHomeWelcome.setEditable(false);
        txtHomeWelcome.setColumns(20);
        txtHomeWelcome.setRows(5);
        txtHomeWelcome.setText("Welcome to the KEVMS (Kerry Eco Voyage Management System)!\nThis dashboard allows you to monitor sea conditions, track fleet performance, and conduct interactive staff training.");
        txtHomeWelcome.setOpaque(false);
        jScrollPane4.setViewportView(txtHomeWelcome);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnNavSafety, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNavTour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(btnNavTraining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane4)
                            .addComponent(jLabel3))))
                .addGap(87, 87, 87))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNavSafety)
                    .addComponent(btnNavTour)
                    .addComponent(btnNavTraining))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanel4);

        findMaritimeSafetyServicebtn.setBackground(new java.awt.Color(235, 217, 52));
        findMaritimeSafetyServicebtn.setText("Find Service");
        findMaritimeSafetyServicebtn.addActionListener(this::findMaritimeSafetyServicebtnActionPerformed);

        lblStatusSafety.setText("Status: Disconnected");

        txtAreaCode.setForeground(new java.awt.Color(153, 153, 153));
        txtAreaCode.setText("Input Area Code");
        txtAreaCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAreaCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAreaCodeFocusLost(evt);
            }
        });
        txtAreaCode.addActionListener(this::txtAreaCodeActionPerformed);

        checkSeaConditionBtn.setBackground(new java.awt.Color(52, 128, 235));
        checkSeaConditionBtn.setForeground(new java.awt.Color(242, 242, 242));
        checkSeaConditionBtn.setText("Check Conditions");
        checkSeaConditionBtn.addActionListener(this::checkSeaConditionBtnActionPerformed);

        txtResultSafety.setColumns(20);
        txtResultSafety.setRows(5);
        jScrollPane1.setViewportView(txtResultSafety);

        txtVesselId.setForeground(new java.awt.Color(153, 153, 153));
        txtVesselId.setText("Input Vessel ID");
        txtVesselId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVesselIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVesselIdFocusLost(evt);
            }
        });
        txtVesselId.addActionListener(this::txtVesselIdActionPerformed);

        startMonitoringBtn.setBackground(new java.awt.Color(52, 128, 235));
        startMonitoringBtn.setForeground(new java.awt.Color(242, 242, 242));
        startMonitoringBtn.setText("Start Monitoring Alerts");
        startMonitoringBtn.addActionListener(this::startMonitoringBtnActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVesselId)
                            .addComponent(txtAreaCode))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startMonitoringBtn)
                            .addComponent(checkSeaConditionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(199, 199, 199))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(findMaritimeSafetyServicebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatusSafety)
                        .addGap(138, 138, 138)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findMaritimeSafetyServicebtn)
                    .addComponent(lblStatusSafety))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAreaCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkSeaConditionBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVesselId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startMonitoringBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Maritime Safety", jPanel2);

        findTourOperationsServicebtn.setBackground(new java.awt.Color(235, 217, 52));
        findTourOperationsServicebtn.setText("Find Your Service");
        findTourOperationsServicebtn.addActionListener(this::findTourOperationsServicebtnActionPerformed);

        lblStatusTour.setText("Status: Disconnected");

        txtStaffId.setForeground(new java.awt.Color(153, 153, 153));
        txtStaffId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStaffId.setText("Input Staff ID");
        txtStaffId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStaffIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStaffIdFocusLost(evt);
            }
        });

        btnGetPerformance.setBackground(new java.awt.Color(52, 128, 235));
        btnGetPerformance.setForeground(new java.awt.Color(242, 242, 242));
        btnGetPerformance.setText("Get Performance Score");
        btnGetPerformance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGetPerformance.addActionListener(this::btnGetPerformanceActionPerformed);

        txtResultTour.setColumns(20);
        txtResultTour.setRows(5);
        jScrollPane2.setViewportView(txtResultTour);

        btnStartVoyage.setBackground(new java.awt.Color(52, 128, 235));
        btnStartVoyage.setForeground(new java.awt.Color(242, 242, 242));
        btnStartVoyage.setText("Simulate Voyage Telemetry");
        btnStartVoyage.addActionListener(this::btnStartVoyageActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnStartVoyage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtStaffId)
                                    .addComponent(findTourOperationsServicebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStatusTour)
                                    .addComponent(btnGetPerformance))))
                        .addGap(0, 180, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findTourOperationsServicebtn)
                    .addComponent(lblStatusTour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetPerformance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStartVoyage)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tour Operations", jPanel1);

        findTrainingHubServicebtn.setBackground(new java.awt.Color(235, 217, 52));
        findTrainingHubServicebtn.setText("Find Training Hub");
        findTrainingHubServicebtn.addActionListener(this::findTrainingHubServicebtnActionPerformed);

        lblStatusTraining.setText("Status: Disconnected");

        txtTrainingStaffId.setForeground(new java.awt.Color(153, 153, 153));
        txtTrainingStaffId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTrainingStaffId.setText("Input Staff Name");
        txtTrainingStaffId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTrainingStaffIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTrainingStaffIdFocusLost(evt);
            }
        });
        txtTrainingStaffId.addActionListener(this::txtTrainingStaffIdActionPerformed);

        btnStartTraining.setBackground(new java.awt.Color(52, 128, 235));
        btnStartTraining.setForeground(new java.awt.Color(242, 242, 242));
        btnStartTraining.setText("Start Navigation Simulation");
        btnStartTraining.addActionListener(this::btnStartTrainingActionPerformed);

        txtResultTraining.setColumns(20);
        txtResultTraining.setRows(5);
        jScrollPane3.setViewportView(txtResultTraining);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTrainingStaffId)
                            .addComponent(findTrainingHubServicebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatusTraining)
                            .addComponent(btnStartTraining))
                        .addGap(0, 159, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findTrainingHubServicebtn)
                    .addComponent(lblStatusTraining))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrainingStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStartTraining))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Staff Training", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void startMonitoringBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startMonitoringBtnActionPerformed
        // TODO add your handling code here:
        if (safetyHost == null || safetyPort == 0){
            txtResultSafety.append("Error: Please click 'Find Service' first!\n");
            return;
        }

        new Thread(() -> {
            ManagedChannel channel = ManagedChannelBuilder.forAddress(safetyHost, safetyPort).usePlaintext().build();
            
            // ADVANCED: Create a Cancellable Context to stop the stream early
            Context.CancellableContext cancellableContext = Context.current().withCancellation();
            
            cancellableContext.run(() -> {
                try {
                    int vesselId = Integer.parseInt(txtVesselId.getText());
                    MaritimeSafetyMonitorGrpc.MaritimeSafetyMonitorBlockingStub stub = 
                            MaritimeSafetyMonitorGrpc.newBlockingStub(channel);

                    VesselRequest request = VesselRequest.newBuilder().setVesselId(vesselId).build();
                    javax.swing.SwingUtilities.invokeLater(() -> txtResultSafety.append(">>> Starting alert monitor for Vessel: " + vesselId + "\n"));

                    java.util.Iterator<SafetyAlert> alerts = stub.streamEmergencyAlerts(request);

                    int alertCount = 0;
                    while (alerts.hasNext()) {
                        SafetyAlert alert = alerts.next();
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            txtResultSafety.append("ALERT [Risk " + alert.getRiskLevel() + "]: " + alert.getAlertMessage() + "\n");
                        });
                        
                        // ADVANCED: Cancelling of Messages. Stop receiving after 3 alerts.
                        alertCount++;
                        if (alertCount >= 3) {
                            javax.swing.SwingUtilities.invokeLater(() -> txtResultSafety.append(">>> Auto-cancelling stream after 3 alerts...\n"));
                            cancellableContext.cancel(new RuntimeException("User cancelled the stream early."));
                            break;
                        }
                    }

                } catch (StatusRuntimeException e) {
                    // It will throw a CANCELLED status when we break the context, which is expected!
                    if (e.getStatus().getCode() != Status.Code.CANCELLED) {
                        javax.swing.SwingUtilities.invokeLater(() -> txtResultSafety.append("Stream Error: " + e.getStatus().getDescription() + "\n"));
                    }
                } catch (Exception e) {
                    javax.swing.SwingUtilities.invokeLater(() -> txtResultSafety.append("Error: " + e.getMessage() + "\n"));
                } finally {
                    channel.shutdown();
                }
            });
        }).start();
    }//GEN-LAST:event_startMonitoringBtnActionPerformed

    private void checkSeaConditionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSeaConditionBtnActionPerformed
        // TODO add your handling code here:
        // Validation to find the service first 
        if (safetyHost == null || safetyPort == 0) {
            txtResultSafety.append("Error: Please click 'Find Service' first!\n");
            return;
        }

        ManagedChannel channel = ManagedChannelBuilder.forAddress(safetyHost, safetyPort).usePlaintext().build();
        try {
            // Get the input from the Text Field
            int areaCode = Integer.parseInt(txtAreaCode.getText());

            // ADVANCED: Create Metadata (Authentication Token)
            Metadata header = new Metadata();
            Metadata.Key<String> key = Metadata.Key.of("auth-token", Metadata.ASCII_STRING_MARSHALLER);
            header.put(key, "kevms-secure-token-123");

            // Attach Metadata to Stub
            MaritimeSafetyMonitorGrpc.MaritimeSafetyMonitorBlockingStub stub = 
                    MaritimeSafetyMonitorGrpc.newBlockingStub(channel);
            stub = MetadataUtils.attachHeaders(stub, header);

            // ADVANCED: Add a Deadline (Timeout after 5 seconds)
            stub = stub.withDeadlineAfter(5, TimeUnit.SECONDS);
            
            //Build the request
            ConditionRequest request = ConditionRequest.newBuilder().setAreaCode(areaCode).build();
            
            //Call the RPC
            ConditionReport response = stub.checkSeaConditions(request);
            
            
            //Update the UI with response
            txtResultSafety.append(">>> KEVMS is checking this area: " + areaCode + "\n");
            txtResultSafety.append("Result: " + (response.getIsSafe() ? "SAFE" : "DANGEROUS") + "\n");
            txtResultSafety.append("Wave Height: " + response.getWaveHeight() + "m\n");
            txtResultSafety.append("----------------------------\n");

        } catch (NumberFormatException e) {
            txtResultSafety.append("Input Error: Please enter a numeric Area Code.\n");
        } catch (StatusRuntimeException e) {
            // ADVANCED: Remote Error Handling
            txtResultSafety.append("REMOTE ERROR [" + e.getStatus().getCode() + "]: " + e.getStatus().getDescription() + "\n");
        } catch (Exception e) {
            txtResultSafety.append("Error: " + e.getMessage() + "\n");
        } finally {
            channel.shutdown(); //clean up
        }
    }//GEN-LAST:event_checkSeaConditionBtnActionPerformed

    private void txtAreaCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaCodeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtAreaCodeActionPerformed

    private void findMaritimeSafetyServicebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findMaritimeSafetyServicebtnActionPerformed
        // TODO add your handling code here:
        ServiceDiscovery discovery = new ServiceDiscovery();
        discovery.discover("_grpc._tcp.local.");

        String host = discovery.getHost();
        int port = discovery.getPort();        if (host != null) {
            lblStatusSafety.setText("Connected to: " + host + ":" + port);
            // Save these to global variables so other buttons can use them
            this.safetyHost = host;
            this.safetyPort = port;
        } else {
            lblStatusSafety.setText("Service not found!");
        }
    }//GEN-LAST:event_findMaritimeSafetyServicebtnActionPerformed

    private void findTourOperationsServicebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findTourOperationsServicebtnActionPerformed
        // TODO add your handling code here:
        ServiceDiscovery discovery = new ServiceDiscovery();
        discovery.discover("_grpc._tcp.local.");

        // In a real scenario, you'd filter by name "TourOperations" 
        // For now, we'll assume it finds the correct one or use the host/port logic
        this.tourHost = discovery.getHost();
        this.tourPort = discovery.getPort();

        if (tourHost != null) {
            lblStatusTour.setText("Connected to: " + tourHost + ":" + tourPort);
        } else {
            lblStatusTour.setText("Service not found!");
        }
    }//GEN-LAST:event_findTourOperationsServicebtnActionPerformed

    private void btnGetPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetPerformanceActionPerformed
        // TODO add your handling code here:
        if (tourHost == null) {
            txtResultTour.append("Error: Please click 'Find Service' first!\n");
            return;
        }

        ManagedChannel channel = ManagedChannelBuilder.forAddress(tourHost, tourPort).usePlaintext().build();
        try {
            int staffId = Integer.parseInt(txtStaffId.getText());
            TourOperationsTrackerGrpc.TourOperationsTrackerBlockingStub stub = 
                    TourOperationsTrackerGrpc.newBlockingStub(channel)
                    .withDeadlineAfter(5, TimeUnit.SECONDS); // ADVANCED: Deadline

            StaffRequest request = StaffRequest.newBuilder().setStaffId(staffId).build();
            PerformanceScore response = stub.getStaffPerformance(request);

            txtResultTour.append("Staff ID " + staffId + " Efficiency: " + response.getEfficiencyRating() + "%\n");
        } catch (StatusRuntimeException e) {
            txtResultTour.append("RPC Failed: " + e.getStatus() + "\n");
        } finally {
            channel.shutdown();
        }
    }//GEN-LAST:event_btnGetPerformanceActionPerformed

    private void btnStartVoyageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartVoyageActionPerformed
        // TODO add your handling code here:
        if (tourHost == null) {
            txtResultTour.append("Error: Please click 'Find Service' first!\n");
            return;
        }

        new Thread(() -> {
            ManagedChannel channel = ManagedChannelBuilder.forAddress(tourHost, tourPort).usePlaintext().build();
            TourOperationsTrackerGrpc.TourOperationsTrackerStub asyncStub = TourOperationsTrackerGrpc.newStub(channel);

            StreamObserver<VoyageSummary> responseObserver = new StreamObserver<VoyageSummary>() {
                @Override
                public void onNext(VoyageSummary summary) {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        txtResultTour.append("----------------------------\n");
                        txtResultTour.append("SERVER RESPONSE: Voyage Summary Received!\n");
                        txtResultTour.append("Total Distance: " + summary.getTotalDistance() + "km\n");
                        txtResultTour.append("Avg Efficiency: " + summary.getAverageEfficiency() + "%\n");
                        txtResultTour.append("----------------------------\n");
                    });
                }

                @Override
                public void onError(Throwable t) {
                    javax.swing.SwingUtilities.invokeLater(() -> txtResultTour.append("Stream Error: " + Status.fromThrowable(t).getDescription() + "\n"));
                }

                @Override
                public void onCompleted() {
                    channel.shutdown();
                }
            };

            StreamObserver<TelemetryData> requestObserver = asyncStub.recordVoyageTelemetry(responseObserver);

            try {
                javax.swing.SwingUtilities.invokeLater(() -> txtResultTour.append(">>> Starting Telemetry Stream...\n"));

                TelemetryData p1 = TelemetryData.newBuilder().setLatitude(51.772).setLongitude(-10.539).setCurrentFuelFlow(4.2f).build();
                javax.swing.SwingUtilities.invokeLater(() -> txtResultTour.append("Sending Telemetry: Lat " + p1.getLatitude() + "\n"));
                requestObserver.onNext(p1);
                Thread.sleep(1500); 

                TelemetryData p2 = TelemetryData.newBuilder().setLatitude(51.778).setLongitude(-10.545).setCurrentFuelFlow(4.1f).build();
                javax.swing.SwingUtilities.invokeLater(() -> txtResultTour.append("Sending Telemetry: Lat " + p2.getLatitude() + "\n"));
                requestObserver.onNext(p2);

                javax.swing.SwingUtilities.invokeLater(() -> txtResultTour.append(">>> All telemetry sent. Waiting for summary...\n"));
                requestObserver.onCompleted();

            } catch (Exception e) {
                requestObserver.onError(e); // ADVANCED: Telling server an error occurred mid-stream
            }
        }).start();
    }//GEN-LAST:event_btnStartVoyageActionPerformed

    private void findTrainingHubServicebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findTrainingHubServicebtnActionPerformed
        // TODO add your handling code here:
        ServiceDiscovery discovery = new ServiceDiscovery();
        discovery.discover("_grpc._tcp.local.");

        this.trainingHost = discovery.getHost();
        this.trainingPort = discovery.getPort();

        if (trainingHost != null) {
            lblStatusTraining.setText("Connected: " + trainingHost + ":" + trainingPort);
        } else {
            lblStatusTraining.setText("Service not found!");
        }
    }//GEN-LAST:event_findTrainingHubServicebtnActionPerformed

    private void btnStartTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartTrainingActionPerformed
        // TODO add your handling code here:
        if (trainingHost == null) {
            txtResultTraining.append("Error: Please click 'Find Service' first!\n");
            return;
        }

        new Thread(() -> {
            ManagedChannel channel = ManagedChannelBuilder.forAddress(trainingHost, trainingPort).usePlaintext().build();
            StaffTrainingHubGrpc.StaffTrainingHubStub asyncStub = StaffTrainingHubGrpc.newStub(channel);

            StreamObserver<InstructorFeedback> responseObserver = new StreamObserver<InstructorFeedback>() {
                @Override
                public void onNext(InstructorFeedback feedback) {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        txtResultTraining.append("[INSTRUCTOR]: " + feedback.getInstruction()
                                + " (Error Margin: " + feedback.getCurrentErrorMargin() + ")\n");
                    });
                }

                @Override
                public void onError(Throwable t) {
                    javax.swing.SwingUtilities.invokeLater(() -> txtResultTraining.append("Training Error: " + Status.fromThrowable(t).getCode() + "\n"));
                }

                @Override
                public void onCompleted() {
                    javax.swing.SwingUtilities.invokeLater(() -> txtResultTraining.append(">>> Training Session Finalized.\n"));
                    channel.shutdown();
                }
            };

            StreamObserver<TraineeAction> requestObserver = asyncStub.interactiveNavigationTraining(responseObserver);

            try {
                String name = txtTrainingStaffId.getText();
                javax.swing.SwingUtilities.invokeLater(() -> txtResultTraining.append(">>> Starting Session for " + name + "...\n"));

                javax.swing.SwingUtilities.invokeLater(() -> txtResultTraining.append("[YOU]: Hard turn to 15 degrees.\n"));
                requestObserver.onNext(TraineeAction.newBuilder().setStaffId(name).setRudderAngle(15.0f).setEngineThrottle(60).build());
                Thread.sleep(2000);

                javax.swing.SwingUtilities.invokeLater(() -> txtResultTraining.append("[YOU]: Adjusting to 5 degrees.\n"));
                requestObserver.onNext(TraineeAction.newBuilder().setStaffId(name).setRudderAngle(5.0f).setEngineThrottle(50).build());
                Thread.sleep(2000);

                requestObserver.onCompleted();

            } catch (Exception e) {
                requestObserver.onError(e);
            }
        }).start();
    }//GEN-LAST:event_btnStartTrainingActionPerformed

    private void btnNavSafetyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavSafetyActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnNavSafetyActionPerformed

    private void btnNavTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavTourActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnNavTourActionPerformed

    private void btnNavTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavTrainingActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnNavTrainingActionPerformed

    private void txtAreaCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAreaCodeFocusGained
        // TODO add your handling code here:
        // When I click into the box, if the text is still the placeholder, clear it.
        if (txtAreaCode.getText().equals("Input Area Code")) {
            txtAreaCode.setText("");
        }
    }//GEN-LAST:event_txtAreaCodeFocusGained

    private void txtAreaCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAreaCodeFocusLost
        // TODO add your handling code here:
        // When the user is not clicking to the box, put the placeholder back.
        if (txtAreaCode.getText().isEmpty()) {
            txtAreaCode.setForeground(new java.awt.Color(153, 153, 153));
            txtAreaCode.setText("Input Area Code");
        }
    }//GEN-LAST:event_txtAreaCodeFocusLost

    private void txtVesselIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVesselIdFocusGained
        // TODO add your handling code here:
        // When I click into the box, if the text is still the placeholder, clear it.
        if (txtVesselId.getText().equals("Input Vessel ID")) {
            txtVesselId.setText("");
        }
    }//GEN-LAST:event_txtVesselIdFocusGained

    private void txtVesselIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVesselIdFocusLost
        // TODO add your handling code here:
        // When the user is not clicking to the box, put the placeholder back.
        if (txtVesselId.getText().isEmpty()) {
            txtVesselId.setForeground(new java.awt.Color(153, 153, 153));
            txtVesselId.setText("Input Vessel ID");
        }
    }//GEN-LAST:event_txtVesselIdFocusLost

    private void txtStaffIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStaffIdFocusGained
        // TODO add your handling code here:
        // When I click into the box, if the text is still the placeholder, clear it.
        if (txtStaffId.getText().equals("Input Staff ID")) {
            txtStaffId.setText("");
        }
    }//GEN-LAST:event_txtStaffIdFocusGained

    private void txtStaffIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStaffIdFocusLost
        // TODO add your handling code here:
        // When the user is not clicking to the box, put the placeholder back.
        if (txtStaffId.getText().isEmpty()) {
            txtStaffId.setForeground(new java.awt.Color(153, 153, 153));
            txtStaffId.setText("Input Staff ID");
        }
    }//GEN-LAST:event_txtStaffIdFocusLost

    private void txtVesselIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVesselIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVesselIdActionPerformed

    private void txtTrainingStaffIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTrainingStaffIdFocusGained
        // TODO add your handling code here:
        // When I click into the box, if the text is still the placeholder, clear it.
        if (txtTrainingStaffId.getText().equals("Input Staff Name")) {
            txtTrainingStaffId.setText("");
        }
    }//GEN-LAST:event_txtTrainingStaffIdFocusGained

    private void txtTrainingStaffIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTrainingStaffIdFocusLost
        // TODO add your handling code here:
        // When the user is not clicking to the box, put the placeholder back.
        if (txtTrainingStaffId.getText().isEmpty()) {
            txtTrainingStaffId.setForeground(new java.awt.Color(153, 153, 153));
            txtTrainingStaffId.setText("Input Staff Name");
        }
    }//GEN-LAST:event_txtTrainingStaffIdFocusLost

    private void txtTrainingStaffIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrainingStaffIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrainingStaffIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KEVMS_GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetPerformance;
    private javax.swing.JButton btnNavSafety;
    private javax.swing.JButton btnNavTour;
    private javax.swing.JButton btnNavTraining;
    private javax.swing.JButton btnStartTraining;
    private javax.swing.JButton btnStartVoyage;
    private javax.swing.JButton checkSeaConditionBtn;
    private javax.swing.JButton findMaritimeSafetyServicebtn;
    private javax.swing.JButton findTourOperationsServicebtn;
    private javax.swing.JButton findTrainingHubServicebtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblStatusSafety;
    private javax.swing.JLabel lblStatusTour;
    private javax.swing.JLabel lblStatusTraining;
    private javax.swing.JButton startMonitoringBtn;
    private javax.swing.JTextField txtAreaCode;
    private javax.swing.JTextArea txtHomeWelcome;
    private javax.swing.JTextArea txtResultSafety;
    private javax.swing.JTextArea txtResultTour;
    private javax.swing.JTextArea txtResultTraining;
    private javax.swing.JTextField txtStaffId;
    private javax.swing.JTextField txtTrainingStaffId;
    private javax.swing.JTextField txtVesselId;
    // End of variables declaration//GEN-END:variables
}
