/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distsys.kevms;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import generated.grpc.CA.maritimesafety.*;

/**
 *
 * @author andre
 */
public class KEVMS_GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KEVMS_GUI.class.getName());
    private String safetyHost;
    private int safetyPort;
            
    /**
     * Creates new form KEVMS_GUI
     */
    public KEVMS_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblStatusSafety = new javax.swing.JLabel();
        txtAreaCode = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultSafety = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtVesselId = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Find Service");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        lblStatusSafety.setText("Status: Disconnected");

        txtAreaCode.setText("Area Code Input");
        txtAreaCode.addActionListener(this::txtAreaCodeActionPerformed);

        jButton2.setText("Check Conditions");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        txtResultSafety.setColumns(20);
        txtResultSafety.setRows(5);
        jScrollPane1.setViewportView(txtResultSafety);

        jLabel1.setText("Vessel ID");

        txtVesselId.setText("Vessel ID Input");

        jButton3.setText("Start Monitoring Alerts");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel2.setText("Area Code");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStatusSafety))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtVesselId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtAreaCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))))
                        .addGap(0, 157, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lblStatusSafety))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAreaCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVesselId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Maritime Safety", jPanel2);
        jTabbedPane1.addTab("Tour Operations", jTabbedPane2);
        jTabbedPane1.addTab("Staff Training", jTabbedPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ServiceDiscovery discovery = new ServiceDiscovery();
        discovery.discover("_grpc._tcp.local.");

        String host = discovery.getHost();
        int port = discovery.getPort();        if (host != null) {
            lblStatusSafety.setText("Connected to: " + host + ":" + port);
            // Save these to global variables so other buttons can use them
            this.safetyHost = host;
            this.safetyPort = port;
        } else {
            lblStatusSafety.setText("Service not found!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAreaCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaCodeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtAreaCodeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // 1. Validation: Make sure we found the service first
        if (safetyHost == null || safetyPort == 0) {
            txtResultSafety.append("Error: Please click 'Find Service' first!\n");
            return;
        }

        try {
            // 2. Get the input from the Text Field
            int areaCode = Integer.parseInt(txtAreaCode.getText());

            // 3. Create the Channel and Stub
            // (Note: In a real app, you might keep the channel open, but for a simple CA, 
            // creating it here is fine)
            ManagedChannel channel = ManagedChannelBuilder.forAddress(safetyHost, safetyPort)
                    .usePlaintext()
                    .build();

            MaritimeSafetyMonitorGrpc.MaritimeSafetyMonitorBlockingStub stub
                    = MaritimeSafetyMonitorGrpc.newBlockingStub(channel);

            // 4. Build the Request
            ConditionRequest request = ConditionRequest.newBuilder()
                    .setAreaCode(areaCode)
                    .build();

            // 5. Call the Server (The Simple RPC)
            ConditionReport response = stub.checkSeaConditions(request);

            // 6. Update the UI with the response
            txtResultSafety.append(">>> KEVMS is checking this area: " + areaCode + "\n");
            txtResultSafety.append("Result: " + (response.getIsSafe() ? "SAFE" : "DANGEROUS") + "\n");
            txtResultSafety.append("Wave Height: " + response.getWaveHeight() + "m\n");
            txtResultSafety.append("----------------------------\n");

            // 7. Clean up
            channel.shutdown();

        } catch (NumberFormatException e) {
            txtResultSafety.append("Input Error: Please enter a numeric Area Code (e.g., 101).\n");
        } catch (Exception e) {
            txtResultSafety.append("RPC Error: " + e.getMessage() + "\n");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (safetyHost == null || safetyPort == 0) {
            txtResultSafety.append("Error: Please click 'Find Service' first!\n");
            return;
        }

        // Start a new thread so the UI stays responsive while waiting for alerts
        new Thread(() -> {
            ManagedChannel channel = null;
            try {
                int vesselId = Integer.parseInt(txtVesselId.getText());

                channel = ManagedChannelBuilder.forAddress(safetyHost, safetyPort)
                        .usePlaintext()
                        .build();

                MaritimeSafetyMonitorGrpc.MaritimeSafetyMonitorBlockingStub stub
                        = MaritimeSafetyMonitorGrpc.newBlockingStub(channel);

                VesselRequest request = VesselRequest.newBuilder()
                        .setVesselId(vesselId)
                        .build();

                txtResultSafety.append(">>> Starting alert monitor for Vessel: " + vesselId + "\n");

                // This line returns an Iterator that waits for the server to send data
                java.util.Iterator<SafetyAlert> alerts = stub.streamEmergencyAlerts(request);

                // This while-loop blocks the thread until a new alert arrives
                while (alerts.hasNext()) {
                    SafetyAlert alert = alerts.next();

                    // Use SwingUtilities to safely update the GUI from a background thread
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        txtResultSafety.append("ALERT [Risk " + alert.getRiskLevel() + "]: "
                                + alert.getAlertMessage() + "\n");
                    });
                }

                javax.swing.SwingUtilities.invokeLater(() -> {
                    txtResultSafety.append(">>> Alert stream ended by server.\n");
                });

            } catch (NumberFormatException e) {
                txtResultSafety.append("Input Error: Vessel ID must be a number.\n");
            } catch (Exception e) {
                txtResultSafety.append("Streaming Error: " + e.getMessage() + "\n");
            } finally {
                if (channel != null) {
                    channel.shutdown();
                }
            }
        }).start(); // Don't forget to start the thread!
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KEVMS_GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lblStatusSafety;
    private javax.swing.JTextField txtAreaCode;
    private javax.swing.JTextArea txtResultSafety;
    private javax.swing.JTextField txtVesselId;
    // End of variables declaration//GEN-END:variables
}
